# Generated by Django 4.1.7 on 2023-03-25 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allergy_pic', models.ImageField(blank=True, null=True, upload_to='Allergy_pics')),
                ('arabicDescription', models.TextField(max_length=500)),
                ('englishDescription', models.TextField(max_length=500)),
                ('arabicName', models.CharField(max_length=50)),
                ('englishName', models.CharField(max_length=50)),
                ('arabicSymptoms', models.TextField(max_length=255)),
                ('englishSymptoms', models.TextField(max_length=255)),
                ('arabicPrevention', models.TextField(max_length=255)),
                ('englishPrevention', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EMAIL_VERIFICATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arabicName', models.TextField(max_length=500)),
                ('englishName', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_doctor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodAllergy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodAllergies_App.allergy')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodAllergies_App.food')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arabicName', models.CharField(max_length=50)),
                ('englishName', models.CharField(max_length=50)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodAllergies_App.allergy')),
                ('food', models.ManyToManyField(to='foodAllergies_App.food')),
            ],
        ),
    ]
