# Generated by Django 4.1.7 on 2023-03-25 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodAllergies_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodAllergy',
        ),
    ]
