# Generated by Django 4.1.7 on 2023-03-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodAllergies_App', '0003_alter_category_allergy_alter_category_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='food',
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodAllergies_App.category')),
                ('foods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodAllergies_App.food')),
            ],
        ),
    ]
