# Generated by Django 4.1.7 on 2023-03-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodAllergies_App', '0004_remove_category_food_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAllergy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodAllergies_App.allergy')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='allergy',
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
        migrations.AddField(
            model_name='foodallergy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodAllergies_App.category'),
        ),
        migrations.AddField(
            model_name='foodallergy',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodAllergies_App.food'),
        ),
    ]
